version: 0.0
os: linux

files:
  - source: /duri-aws-build.zip
    destination: /home/ubuntu/duri
permissions:
  - object: /home/ubuntu/duri/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: duri/scripts/deploy.sh
      timeout: 60
      runas: ubuntu